# Generated by Django 3.0.7 on 2020-08-18 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('compra', models.CharField(default='Nome', max_length=250)),
                ('processo', models.CharField(default='Lideranca', max_length=250)),
                ('data_publicacao', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('valor_estimado', models.FloatField(blank=True, default=0)),
                ('valor_min', models.FloatField(blank=True, default=0)),
                ('valor_medio', models.FloatField(blank=True, default=0)),
                ('valor_max', models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TotalCompra',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('valor_min', models.FloatField(blank=True, default=0)),
                ('valor_medio', models.FloatField(blank=True, default=0)),
                ('valor_max', models.FloatField(blank=True, default=0)),
            ],
        ),
    ]
